file_version: 1
models:
  user:
    fields:
      id:
        type: long
      username:
        type: string
generators:
  -
    type: go_gin_rest_api
    relative_path: my_gin_rest_api
    options:
      name: my-gin-rest-api
      friendly_name: My Gin REST API
      description: This is an example of a gin REST API!
      package:
        name: 'github.com/comfortablynumb/goginrestapi'
      actions:
        - READ
        - CREATE
        - UPDATE
        - DELETE